export enum AuthStatus {
  USER_EXIST = "USER_EXIST",
  USER_NOT_EXIST = "USER_NOT_EXIST",
  USER_EXIST_WITH_EMAIL = "USER_EXIST_WITH_EMAIL",
  LOGGED_IN = "LOGGED_IN",
  REGISTER_REQUIRED = "REGISTER_REQUIRED",
  REGISTERED = "REGISTERED",
  ERROR = "ERROR",
}
